/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.net.MalformedURLException;

public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        //TestCases tests = new TestCases(); // Initialize your test class
        //01. SearchAmazon searchAmazon = new SearchAmazon();
        HyperlinkCount hyperlinkCount = new HyperlinkCount();


        // TODO: call your test case functions one after other here

        //tests.testCase01();
        //01. searchAmazon.testCase01();
        hyperlinkCount.testCase01();

        // END Tests

        //01. searchAmazon.endTest(); // End your test by clearning connections and closing browser
        hyperlinkCount.endTest();
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
